-- https://school.programmers.co.kr/learn/courses/30/lessons/131536

SELECT USER_ID, PRODUCT_ID
FROM (SELECT USER_ID, PRODUCT_ID, COUNT(*) AS PURCHASE_CNT
     FROM ONLINE_SALE
     GROUP BY USER_ID, PRODUCT_ID) T
    
WHERE T.PURCHASE_CNT >= 2
ORDER BY USER_ID ASC, PRODUCT_ID DESC